CREATE TABLE Tipo_Rebanho(
	ID_Tipo INT NOT NULL IDENTITY(1,1),
	Descricao VARCHAR(MAX) NOT NULL,
	Situacao BIT NULL DEFAULT 1,
	DataInclusao DATETIME NULL DEFAULT GETDATE(),
	DataAlteracao DATETIME NULL,
	DataExclusao DATETIME NULL,
	CONSTRAINT PK_Tipo_Rebanho PRIMARY KEY (ID_Tipo)
)
GO
