CREATE TABLE Pais (
	ID_Pais int IDENTITY (1, 1) NOT NULL,
	Sigla_Pais char (3) NOT NULL,
	Cod_Idioma char (2) NOT NULL,
	Descricao_Pais varchar (MAX) NULL,
	Situacao BIT NULL DEFAULT 1,
	DataInclusao DATETIME NULL DEFAULT GETDATE(),
	DataAlteracao DATETIME NULL,
	DataExclusao DATETIME NULL,
	CONSTRAINT PK_Pais PRIMARY KEY (ID_Pais)
)
GO

SET IDENTITY_INSERT Pais ON

INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (1, 'AFG', 'PS', 'Afeganistão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (2, 'AFS', 'EN', 'África do Sul')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (3, 'AHL', 'NL', 'Antilhas Holandesas')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (4, 'ALB', 'SQ', 'Albânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (5, 'ANB', 'EN', 'Antigua')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (6, 'AND', 'CA', 'Andorra')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (7, 'ANG', 'PT', 'Angola')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (8, 'ARA', 'AR', 'Arábia Saudita')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (9, 'ARG', 'ES', 'Argentina')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (10, 'ARL', 'ES', 'Argélia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (11, 'ARM', 'RU', 'Armênia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (12, 'ASM', 'EN', 'Samoa Americana')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (13, 'ATC', 'EN', 'Antartida')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (14, 'AUS', 'EN', 'Austrália')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (15, 'AUT', 'DE', 'Austria')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (16, 'AZE', 'RU', 'Azerbaijão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (17, 'BAR', 'AR', 'Barein')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (18, 'BEA', 'RU', 'Belarus')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (19, 'BEL', 'FR', 'Bélgica')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (20, 'BEN', 'EN', 'Benin')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (21, 'BER', 'EN', 'Bermudas')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (22, 'BGD', 'BN', 'Bangladesh')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (23, 'BHS', 'EN', 'Bahamas')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (24, 'BIR', 'BM', 'Birmânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (25, 'BKF', 'FR', 'Burkina Fasso')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (26, 'BLZ', 'EN', 'Belize')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (27, 'BOL', 'ES', 'Bolívia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (28, 'BOS', 'EN', 'Bósnia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (29, 'BOT', 'EN', 'Botsuana')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (30, 'BRA', 'PT', 'Brasil')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (31, 'BRB', 'EN', 'Barbados')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (32, 'BRN', 'MS', 'Brunei')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (33, 'BUL', 'BG', 'Bulgária')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (34, 'BUR', 'FR', 'Burundi')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (35, 'BUT', 'DZ', 'Butão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (36, 'CAM', 'EN', 'Camarões')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (37, 'CAN', 'EN', 'Canadá')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (38, 'CAT', 'AR', 'Catar')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (39, 'CAZ', 'RU', 'Cazaquistão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (40, 'CBJ', 'KM', 'Camboja')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (41, 'CBV', 'PT', 'Cabo Verde')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (42, 'CCK', 'EN', 'Ilhas Cocos')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (43, 'CHA', 'FR', 'Chade')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (44, 'CHL', 'ES', 'Chile')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (45, 'CHN', 'ZH', 'China')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (46, 'CHP', 'EL', 'Chipre')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (47, 'CIN', 'EN', 'Cingapura')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (48, 'CMF', 'FR', 'Costa do Marfim')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (49, 'COK', 'EN', 'Ilhas Cook')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (50, 'COL', 'EN', 'Colômbia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (51, 'COM', 'EN', 'Comores')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (52, 'CON', 'FR', 'Congo')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (53, 'CRC', 'ES', 'Costa Rica')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (54, 'CRN', 'KO', 'Coréia do Norte')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (55, 'CRO', 'EN', 'Croácia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (56, 'CRS', 'KO', 'Coréia do Sul')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (57, 'CUB', 'ES', 'Cuba')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (58, 'CXR', 'EN', 'Christmas Island')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (59, 'CYM', 'EN', 'Ilhas Cayman')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (60, 'DIN', 'DA', 'Dinamarca')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (61, 'DJI', 'EN', 'Djibuti')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (62, 'DOM', 'ES', 'República Dominicana')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (63, 'DON', 'EN', 'Dominica')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (64, 'EAU', 'AR', 'Emirados Árabes')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (65, 'EGI', 'AR', 'Egito')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (66, 'ELS', 'ES', 'El Salvador')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (67, 'EQU', 'ES', 'Equador')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (68, 'ERT', 'AR', 'Eritréa')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (69, 'ESC', 'EN', 'Escócia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (70, 'ESH', 'EN', 'Western Sahara')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (71, 'ESP', 'ES', 'Espanha')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (72, 'EST', 'RU', 'Estônia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (73, 'ETP', 'AM', 'Etiópia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (74, 'EUA', 'EN', 'Estados Unidos')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (75, 'FIL', 'FL', 'Filipinas')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (76, 'FIN', 'EN', 'Finlândia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (77, 'FJI', 'EN', 'Fiji')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (78, 'FLK', 'EN', 'Ilhas Falkland')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (79, 'FOR', 'ZH', 'Formosa')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (80, 'FRA', 'FR', 'França')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (81, 'FSM', 'EN', 'Micronésia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (82, 'GAB', 'FR', 'Gabão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (83, 'GAL', 'EN', 'Gales')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (84, 'GAM', 'EN', 'Gâmbia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (85, 'GAN', 'EN', 'Gana')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (86, 'GBR', 'EN', 'Grã-Bretanha')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (87, 'GDL', 'FR', 'Guadalupe')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (88, 'GEO', 'RU', 'Geórgia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (89, 'GFR', 'FR', 'Guiana Francesa')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (90, 'GIB', 'EN', 'Gibraltar')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (91, 'GNB', 'PT', 'Guiné Bissau')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (92, 'GNE', 'ES', 'Guiné')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (93, 'GNQ', 'EN', 'Guiné Equatorial')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (94, 'GRD', 'EN', 'Granada')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (95, 'GRE', 'EL', 'Grécia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (96, 'GRL', 'EN', 'Groênlandia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (97, 'GUA', 'ES', 'Guatemala')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (98, 'GUI', 'EN', 'Guiana')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (99, 'GUM', 'EN', 'Guam')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (100, 'HKG', 'EN', 'Hong Kong')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (101, 'HOL', 'NL', 'Holanda')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (102, 'HON', 'ES', 'Honduras')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (103, 'HTI', 'FR', 'Haiti')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (104, 'HUN', 'HU', 'Hungria')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (105, 'IDN', 'IN', 'Indonésia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (106, 'IEM', 'AR', 'Iêmem')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (107, 'IFA', 'DA', 'Ilhas Faroe')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (108, 'IMH', 'EN', 'Ilhas Marshall')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (109, 'IMS', 'AR', 'Iêmen do Sul')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (110, 'IND', 'HI', 'Índia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (111, 'ING', 'EN', 'Inglaterra')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (112, 'IOT', 'EN', 'Britsh Indian Ocean')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (113, 'IRA', 'FA', 'Irã')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (114, 'IRL', 'EN', 'Irlanda')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (115, 'IRN', 'EN', 'Irlanda do Norte')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (116, 'IRQ', 'AR', 'Iraque')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (117, 'ISL', 'IS', 'Islândia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (118, 'ISR', 'IW', 'Israel')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (119, 'ITA', 'IT', 'Itália')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (120, 'IUG', 'SH', 'Iugoslávia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (121, 'IVA', 'EN', 'Ilhas Vírgens EUA')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (122, 'JAM', 'EN', 'Jamaica')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (123, 'JAP', 'JA', 'Japão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (124, 'JOR', 'AR', 'Jordânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (125, 'KIR', 'EN', 'Kiribati')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (126, 'KNA', 'EN', 'São Cristóvão Nevis')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (127, 'KWT', 'AR', 'Kuweit')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (128, 'LAO', 'LO', 'Laos')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (129, 'LBN', 'AR', 'Líbano')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (130, 'LBR', 'EN', 'Libéria')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (131, 'LCA', 'EN', 'Santa Lúcia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (132, 'LES', 'EN', 'Lesoto')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (133, 'LET', 'RU', 'Letônia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (134, 'LIB', 'AR', 'Líbia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (135, 'LIE', 'DE', 'Liechtenstein')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (136, 'LIT', 'RU', 'Lituânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (137, 'LUX', 'FR', 'Luxemburgo')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (138, 'MAC', 'PT', 'Macau')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (139, 'MAD', 'FR', 'Madagascar')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (140, 'MAL', 'MS', 'Malásia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (141, 'MAR', 'AR', 'Marrocos')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (142, 'MAU', 'EN', 'Maurício')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (143, 'MBQ', 'PT', 'Moçambique')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (144, 'MCD', 'MK', 'Macedônia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (145, 'MDV', 'EN', 'Maldivas')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (146, 'MEX', 'ES', 'México')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (147, 'MGL', 'MN', 'Mongólia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (148, 'MID', 'EN', 'Ilhas Midway')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (149, 'MLI', 'FR', 'Mali')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (150, 'MLT', 'MT', 'Malta')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (151, 'MLV', 'EN', 'Malavi')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (152, 'MMR', 'EN', 'Mianmar')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (153, 'MOL', 'RU', 'Moldova')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (154, 'MON', 'FR', 'Mônaco')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (155, 'MRT', 'FR', 'Martinica')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (156, 'MSR', 'EN', 'Montserrat')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (157, 'MTN', 'AR', 'Mauritânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (158, 'NAM', 'EN', 'Namíbia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (159, 'NCL', 'FR', 'Nova Caledônia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (160, 'NFK', 'EN', 'Ilhas Norfolk')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (161, 'NGA', 'EN', 'Nigéria')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (162, 'NIC', 'ES', 'Nicarágua')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (163, 'NIG', 'FR', 'Niger')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (164, 'NIU', 'EN', 'Niue')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (165, 'NOR', 'NO', 'Noruega')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (166, 'NPL', 'NE', 'Nepal')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (167, 'NRU', 'EN', 'Nauru')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (168, 'NZL', 'EN', 'Nova Zelândia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (169, 'OMA', 'AR', 'Oma')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (170, 'PAN', 'ES', 'Panamá')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (171, 'PAQ', 'UR', 'Paquistão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (172, 'PCI', 'EN', 'Pacific Islands')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (173, 'PCN', 'EN', 'Pitcairn')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (174, 'PER', 'ES', 'Peru')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (175, 'PLF', 'FR', 'Polinésia Francesa')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (176, 'PLU', 'EN', 'Palau')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (177, 'PNG', 'EN', 'Papua Nova Guiné')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (178, 'POL', 'PL', 'Polônia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (179, 'POR', 'PT', 'Portugal')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (180, 'PRG', 'ES', 'Paraguai')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (181, 'PTR', 'ES', 'Porto Rico')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (182, 'QUE', 'SW', 'Quênia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (183, 'QUI', 'RU', 'Quirgistão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (184, 'RCA', 'FR', 'Rep.Centro-Africana')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (185, 'REU', 'FR', 'Reunião')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (186, 'RFA', 'DE', 'Alemanha')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (187, 'ROM', 'RO', 'Romênia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (188, 'RSS', 'RU', 'Rússia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (189, 'RUA', 'FR', 'Ruanda')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (190, 'SAM', 'EN', 'Samoa Ocidental')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (191, 'SEN', 'FR', 'Senegal')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (192, 'SHN', 'EN', 'Ilhas Santa Helena')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (193, 'SIR', 'AR', 'Síria')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (194, 'SLB', 'EN', 'Ilhas Salamão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (195, 'SMR', 'IT', 'San Marino')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (196, 'SOM', 'AR', 'Somália')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (197, 'SPM', 'EN', 'São Pedro Miquelon')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (198, 'SRI', 'SI', 'Sri Lanka')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (199, 'SRL', 'EN', 'Serra Leoa')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (200, 'STP', 'EN', 'São Tomé e Príncipe')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (201, 'SUA', 'EN', 'Suazilândia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (202, 'SUD', 'AR', 'Sudão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (203, 'SUE', 'SV', 'Suécia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (204, 'SUI', 'FR', 'Suiça')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (205, 'SUR', 'NL', 'Suriname')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (206, 'SVK', 'EN', 'Eslováquia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (207, 'SVN', 'EN', 'Eslovênia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (208, 'SYC', 'EN', 'Seychelles')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (209, 'TAD', 'RU', 'Tadjaquistão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (210, 'TAI', 'TH', 'Tailândia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (211, 'TAN', 'EN', 'Tanzânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (212, 'TCA', 'EN', 'Ilhas Turcas Caicos')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (213, 'TCH', 'CS', 'República Tcheca')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (214, 'TGO', 'FR', 'Togo')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (215, 'TKL', 'EN', 'Tokelau')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (216, 'TMP', 'EN', 'Timor')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (217, 'TON', 'EN', 'Tonga')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (218, 'TRT', 'EN', 'Trinidad e Tobago')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (219, 'TUC', 'RU', 'Turcomenistão')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (220, 'TUN', 'AR', 'Tunísia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (221, 'TUR', 'TR', 'Turquia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (222, 'TUV', 'EN', 'Tuvalu')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (223, 'UCR', 'RU', 'Ucrânia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (224, 'UGA', 'EN', 'Uganda')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (225, 'URS', 'RU', 'União Soviética')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (226, 'URU', 'ES', 'Uruguai')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (227, 'UZB', 'RU', 'Uzbekistan')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (228, 'VAT', 'IT', 'Vaticano')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (229, 'VCT', 'EN', 'São Vicente Granadi')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (230, 'VEN', 'ES', 'Venezuela')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (231, 'VGB', 'EN', 'Ilhas Vírgens GBR')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (232, 'VTN', 'VI', 'Vietnã')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (233, 'VUT', 'EN', 'Vanuatu')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (234, 'WAK', 'EN', 'Ilhas Wake')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (235, 'WLF', 'EN', 'Ilhas Wallis Futuna')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (236, 'ZAN', 'EN', 'Zâmbia')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (237, 'ZAR', 'FR', 'Zaire')
INSERT INTO Pais (ID_Pais, Sigla_Pais, Cod_Idioma, Descricao_Pais) VALUES (238, 'ZIN', 'EN', 'Zimbabue')

SET IDENTITY_INSERT Pais OFF
