CREATE TABLE Microregiao (
	ID_Microregiao int IDENTITY (1, 1) NOT NULL,
	Descricao_Microregiao varchar (max) NOT NULL,
	Sigla_UF char (2) NOT NULL,
	Situacao BIT NULL DEFAULT 1,
	DataInclusao DATETIME NULL DEFAULT GETDATE(),
	DataAlteracao DATETIME NULL,
	DataExclusao DATETIME NULL,
	CONSTRAINT PK_Microregiao PRIMARY KEY (ID_Microregiao),
	CONSTRAINT FK_Microregiao_UF FOREIGN KEY (Sigla_UF) REFERENCES Unidades_Federacao(Sigla_UF)
)
GO

SET IDENTITY_INSERT Microregiao ON

INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (1, 'Porto Velho', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (2, 'Guajará-Mirim', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (3, 'Ariquemes', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (4, 'Ji-Paraná', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (5, 'Alvorada D''Oeste', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (6, 'Cacoal', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (7, 'Vilhena', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (8, 'Colorado do Oeste', 'RO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (9, 'Cruzeiro do Sul', 'AC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (10, 'Tarauacá', 'AC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (11, 'Sena Madureira', 'AC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (12, 'Rio Branco', 'AC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (13, 'Brasiléia', 'AC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (14, 'Rio Negro', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (15, 'Japurá', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (16, 'Alto Solimões', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (17, 'Juruá', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (18, 'Tefé', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (19, 'Coari', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (20, 'Manaus', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (21, 'Rio Preto da Eva', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (22, 'Itacoatiara', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (23, 'Parintins', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (24, 'Boca do Acre', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (25, 'Purus', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (26, 'Madeira', 'AM')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (27, 'Boa Vista', 'RR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (28, 'Nordeste de Roraima', 'RR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (29, 'Caracaraí', 'RR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (30, 'Sudeste de Roraima', 'RR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (31, 'Óbidos', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (32, 'Santarém', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (33, 'Almeirim', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (34, 'Portel', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (35, 'Furos de Breves', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (36, 'Arari', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (37, 'Belém', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (38, 'Castanhal', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (39, 'Salgado', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (40, 'Bragantina', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (41, 'Cametá', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (42, 'Tomé-Açu', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (43, 'Guamá', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (44, 'Itaituba', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (45, 'Altamira', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (46, 'Tucuruí', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (47, 'Paragominas', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (48, 'São Félix do Xingu', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (49, 'Parauapebas', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (50, 'Marabá', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (51, 'Redenção', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (52, 'Conceição do Araguaia', 'PA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (53, 'Oiapoque', 'AP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (54, 'Amapá', 'AP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (55, 'Macapá', 'AP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (56, 'Mazagão', 'AP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (57, 'Bico do Papagaio', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (58, 'Araguaína', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (59, 'Miracema do Tocantins', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (60, 'Rio Formoso', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (61, 'Gurupi', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (62, 'Porto Nacional', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (63, 'Jalapão', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (64, 'Dianópolis', 'TO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (65, 'Litoral Ocidental Maranhense', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (66, 'Aglomeração Urbana de São Luís', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (67, 'Rosário', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (68, 'Lençois Maranhenses', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (69, 'Baixada Maranhense', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (70, 'Itapecuru Mirim', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (71, 'Gurupi', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (72, 'Pindaré', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (73, 'Imperatriz', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (74, 'Médio Mearim', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (75, 'Alto Mearim e Grajaú', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (76, 'Presidente Dutra', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (77, 'Baixo Parnaíba Maranhense', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (78, 'Chapadinha', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (79, 'Codó', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (80, 'Coelho Neto', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (81, 'Caxias', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (82, 'Chapadas do Alto Itapecuru', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (83, 'Porto Franco', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (84, 'Gerais de Balsas', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (85, 'Chapadas das Mangabeiras', 'MA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (86, 'Baixo Parnaíba Piauiense', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (87, 'Litoral Piauiense', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (88, 'Teresina', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (89, 'Campo Maior', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (90, 'Médio Parnaíba Piauiense', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (91, 'Valença do Piauí', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (92, 'Alto Parnaíba Piauiense', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (93, 'Bertolínia', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (94, 'Floriano', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (95, 'Alto Médio Gurguéia', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (96, 'São Raimundo Nonato', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (97, 'Chapadas do Extremo Sul Piauiense', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (98, 'Picos', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (99, 'Pio IX', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (100, 'Alto Médio Canindé', 'PI')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (101, 'Litoral de Camocim e Acaraú', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (102, 'Ibiapaba', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (103, 'Coreaú', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (104, 'Meruoca', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (105, 'Sobral', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (106, 'Ipu', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (107, 'Santa Quitéria', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (108, 'Itapipoca', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (109, 'Baixo Curu', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (110, 'Uruburetama', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (111, 'Médio Curu', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (112, 'Canindé', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (113, 'Baturité', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (114, 'Chorozinho', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (115, 'Cascavel', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (116, 'Fortaleza', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (117, 'Pacajus', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (118, 'Sertão de Cratéus', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (119, 'Sertão de Quixeramobim', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (120, 'Sertão de Inhamuns', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (121, 'Sertão de Senador Pompeu', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (122, 'Litoral de Aracati', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (123, 'Baixo Jaguaribe', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (124, 'Médio Jaguaribe', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (125, 'Serra do Pereiro', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (126, 'Iguatu', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (127, 'Várzea Alegre', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (128, 'Lavras da Mangabeira', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (129, 'Chapada do Araripe', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (130, 'Caririaçu', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (131, 'Barro', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (132, 'Cariri', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (133, 'Brejo Santo', 'CE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (134, 'Mossoró', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (135, 'Chapada do Apodi', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (136, 'Médio Oeste', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (137, 'Vale do Açu', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (138, 'Serra de São Miguel', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (139, 'Pau dos Ferros', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (140, 'Umarizal', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (141, 'Macau', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (142, 'Angicos', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (143, 'Serra de Santana', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (144, 'Seridó Ocidental', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (145, 'Seridó Oriental', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (146, 'Baixa Verde', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (147, 'Borborema Potiguar', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (148, 'Agreste Potiguar', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (149, 'Litoral Nordeste', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (150, 'Macaíba', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (151, 'Natal', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (152, 'Litoral Sul', 'RN')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (153, 'Catolé do Rocha', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (154, 'Cajazeiras', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (155, 'Sousa', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (156, 'Patos', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (157, 'Piancó', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (158, 'Itaporanga', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (159, 'Serra do Teixeira', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (160, 'Seridó Ocidental Paraibano', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (161, 'Seridó Oriental Paraibano', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (162, 'Cariri Ocidental', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (163, 'Cariri Oriental', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (164, 'Curimataú Ocidental', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (165, 'Curimataú Oriental', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (166, 'Esperança', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (167, 'Brejo Paraibano', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (168, 'Guarabira', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (169, 'Campina Grande', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (170, 'Itabaiana', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (171, 'Umbuzeiro', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (172, 'Litoral Norte', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (173, 'Sapé', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (174, 'João Pessoa', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (175, 'Litoral Sul', 'PB')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (176, 'Araripina', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (177, 'Salgueiro', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (178, 'Pajeú', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (179, 'Sertão do Moxotó', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (180, 'Petrolina', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (181, 'Itaparica', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (182, 'Vale do Ipanema', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (183, 'Vale do Ipojuca', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (184, 'Alto Capibaribe', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (185, 'Médio Capibaribe', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (186, 'Garanhuns', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (187, 'Brejo Pernambucano', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (188, 'Mata Setentrional Pernambucana', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (189, 'Vitória de Santo Antão', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (190, 'Mata Meridional Pernambucana', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (191, 'Itamaracá', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (192, 'Recife', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (193, 'Suape', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (194, 'Fernando de Noronha', 'PE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (195, 'Serrana do Sertão Alagoano', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (196, 'Alagoana do Sertão do São Francisco', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (197, 'Santana do Ipanema', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (198, 'Batalha', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (199, 'Palmeira dos Índios', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (200, 'Arapiraca', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (201, 'Traipu', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (202, 'Serrana dos Quilombos', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (203, 'Mata Alagoana', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (204, 'Litoral Norte Alagoano', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (205, 'Maceió', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (206, 'São Miguel dos Campos', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (207, 'Penedo', 'AL')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (208, 'Sergipana do Sertão do São Francisco', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (209, 'Carira', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (210, 'Nossa Senhora das Dores', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (211, 'Agreste de Itabaiana', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (212, 'Tobias Barreto', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (213, 'Agreste de Lagarto', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (214, 'Propriá', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (215, 'Cotinguiba', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (216, 'Japaratuba', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (217, 'Baixo Cotinguiba', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (218, 'Aracaju', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (219, 'Boquim', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (220, 'Estância', 'SE')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (221, 'Barreiras', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (222, 'Cotegipe', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (223, 'Santa Maria da Vitória', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (224, 'Juazeiro', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (225, 'Paulo Afonso', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (226, 'Barra', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (227, 'Bom Jesus da Lapa', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (228, 'Senhor do Bonfim', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (229, 'Irecê', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (230, 'Jacobina', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (231, 'Itaberaba', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (232, 'Feira de Santana', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (233, 'Jeremoabo', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (234, 'Euclides da Cunha', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (235, 'Ribeira do Pombal', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (236, 'Serrinha', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (237, 'Alagoinhas', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (238, 'Entre Rios', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (239, 'Catu', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (240, 'Santo Antônio de Jesus', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (241, 'Salvador', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (242, 'Boquira', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (243, 'Seabra', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (244, 'Jequié', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (245, 'Livramento do Brumado', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (246, 'Guanambi', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (247, 'Brumado', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (248, 'Vitória da Conquista', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (249, 'Itapetinga', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (250, 'Valença', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (251, 'Ilhéus-Itabuna', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (252, 'Porto Seguro', 'BA')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (253, 'Unaí', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (254, 'Paracatu', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (255, 'Januária', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (256, 'Janaúba', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (257, 'Salinas', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (258, 'Pirapora', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (259, 'Montes Claros', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (260, 'Grão Mogol', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (261, 'Bocaiúva', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (262, 'Diamantina', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (263, 'Capelinha', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (264, 'Araçuaí', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (265, 'Pedra Azul', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (266, 'Almenara', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (267, 'Teófilo Otoni', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (268, 'Nanuque', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (269, 'Ituiutaba', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (270, 'Uberlândia', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (271, 'Patrocínio', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (272, 'Patos de Minas', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (273, 'Frutal', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (274, 'Uberaba', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (275, 'Araxá', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (276, 'Três Marias', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (277, 'Curvelo', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (278, 'Bom Despacho', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (279, 'Sete Lagoas', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (280, 'Conceição do Mato Dentro', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (281, 'Pará de Minas', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (282, 'Belo Horizonte', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (283, 'Itabira', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (284, 'Itaguara', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (285, 'Ouro Preto', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (286, 'Conselheiro Lafaiete', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (287, 'Guanhães', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (288, 'Peçanha', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (289, 'Governador Valadares', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (290, 'Mantena', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (291, 'Ipatinga', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (292, 'Caratinga', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (293, 'Aimorés', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (294, 'PiŒí', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (295, 'Divinópolis', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (296, 'Formiga', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (297, 'Campo Belo', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (298, 'Oliveira', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (299, 'Passos', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (300, 'São Sebastião do Paraíso', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (301, 'Alfenas', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (302, 'Varginha', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (303, 'Poços de Caldas', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (304, 'Pouso Alegre', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (305, 'Santa Rita do Sapucaí', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (306, 'São Lourenço', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (307, 'Andrelândia', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (308, 'Itajubá', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (309, 'Lavras', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (310, 'São João Del Rei', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (311, 'Barbacena', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (312, 'Ponte Nova', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (313, 'Manhuaçu', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (314, 'Viçosa', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (315, 'Muriaé', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (316, 'Ubá', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (317, 'Juiz de Fora', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (318, 'Cataguases', 'MG')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (319, 'Barra de São Francisco', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (320, 'Nova Venécia', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (321, 'Colatina', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (322, 'Montanha', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (323, 'São Mateus', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (324, 'Linhares', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (325, 'Afonso Cláudio', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (326, 'Santa Teresa', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (327, 'Vitória', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (328, 'Guarapari', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (329, 'Alegre', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (330, 'Cachoeiro de Itapemirim', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (331, 'Itapemirim', 'ES')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (332, 'Itaperuna', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (333, 'Santo Antônio de Pádua', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (334, 'Campos dos Goytacazes', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (335, 'Macaé', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (336, 'Três Rios', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (337, 'Cantagalo-Cordeiro', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (338, 'Nova Friburgo', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (339, 'Santa Maria Madalena', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (340, 'Bacia de São João', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (341, 'Lagos', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (342, 'Vale do Paraíba Fluminense', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (343, 'Barra do Piraí', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (344, 'Baía da Ilha Grande', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (345, 'Vassouras', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (346, 'Serrana', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (347, 'Macacu-Caceribu', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (348, 'Itaguaí', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (349, 'Rio de Janeiro', 'RJ')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (350, 'Jales', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (351, 'Fernandópolis', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (352, 'Votuporanga', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (353, 'São José do Rio Preto', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (354, 'Catanduva', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (355, 'Auriflama', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (356, 'Nhandeara', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (357, 'Novo Horizonte', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (358, 'Barretos', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (359, 'São Joaquim da Barra', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (360, 'Ituverava', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (361, 'Franca', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (362, 'Jaboticabal', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (363, 'Ribeirão Preto', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (364, 'Batatais', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (365, 'Andradina', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (366, 'Araçatuba', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (367, 'Birigui', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (368, 'Lins', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (369, 'Bauru', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (370, 'Jaú', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (371, 'Avaré', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (372, 'Botucatu', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (373, 'Araraquara', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (374, 'São Carlos', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (375, 'Rio Claro', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (376, 'Limeira', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (377, 'Piracicaba', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (378, 'Pirassununga', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (379, 'São João da Boa Vista', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (380, 'Moji-Mirim', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (381, 'Campinas', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (382, 'Amparo', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (383, 'Dracena', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (384, 'Adamantina', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (385, 'Presidente Prudente', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (386, 'Tupã', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (387, 'Marília', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (388, 'Assis', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (389, 'Ourinhos', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (390, 'Itapeva', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (391, 'Itapetininga', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (392, 'Tatuí', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (393, 'Capão Bonito', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (394, 'Piedade', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (395, 'Sorocaba', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (396, 'Jundiaí', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (397, 'Bragança Paulista', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (398, 'Campos do Jordão', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (399, 'São José dos Campos', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (400, 'Guaratinguetá', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (401, 'Bananal', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (402, 'Paraibuna/Paraitinga', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (403, 'Caraguatatuba', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (404, 'Registro', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (405, 'Itanhaém', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (406, 'Osasco', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (407, 'Franco da Rocha', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (408, 'Guarulhos', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (409, 'Itapecerica da Serra', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (410, 'São Paulo', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (411, 'Moji das Cruzes', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (412, 'Santos', 'SP')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (413, 'Paranavaí', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (414, 'Umuarama', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (415, 'Cianorte', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (416, 'Goioerê', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (417, 'Campo Mourão', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (418, 'Astorga', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (419, 'Porecatú', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (420, 'Floraí', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (421, 'Maringá', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (422, 'Apucarana', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (423, 'Londrina', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (424, 'Faxinal', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (425, 'Ivaiporã', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (426, 'Assaí', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (427, 'Cornélio Procópio', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (428, 'Jacarezinho', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (429, 'Ibaití', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (430, 'Wesceslau Braz', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (431, 'Telêmaco Borba', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (432, 'Jaguariaíva', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (433, 'Ponta Grossa', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (434, 'Toledo', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (435, 'Cascavel', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (436, 'Foz do Iguaçu', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (437, 'Capanema', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (438, 'Francisco Beltrão', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (439, 'Pato Branco', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (440, 'Pitanga', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (441, 'Guarapuava', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (442, 'Palmas', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (443, 'Prudentópolis', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (444, 'Irati', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (445, 'União da Vitória', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (446, 'São Mateus do Sul', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (447, 'Cerro Azul', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (448, 'Lapa', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (449, 'Curitiba', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (450, 'Paranaguá', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (451, 'Rio Negro', 'PR')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (452, 'São Miguel d''Oeste', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (453, 'Chapecó', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (454, 'Xanxerê', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (455, 'Joaçaba', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (456, 'Concórdia', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (457, 'Canoinhas', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (458, 'São Bento do Sul', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (459, 'Joinville', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (460, 'Curitibanos', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (461, 'Campos de Lages', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (462, 'Rio do Sul', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (463, 'Blumenau', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (464, 'Itajaí', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (465, 'Ituporanga', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (466, 'Tijucas', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (467, 'Florianópolis', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (468, 'Tabuleiro', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (469, 'Tubarão', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (470, 'Criciúma', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (471, 'Araranguá', 'SC')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (472, 'Santa Rosa', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (473, 'Três Passos', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (474, 'Frederico Westphalen', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (475, 'Erechim', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (476, 'Sananduva', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (477, 'Cerro Largo', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (478, 'Santo Ângelo', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (479, 'Ijuí', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (480, 'Carazinho', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (481, 'Passo Fundo', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (482, 'Cruz Alta', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (483, 'Não-Me-Toque', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (484, 'Soledade', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (485, 'Guaporé', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (486, 'Vacaria', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (487, 'Caxias do Sul', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (488, 'Santiago', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (489, 'Santa Maria', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (490, 'Restinga Seca', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (491, 'Santa Cruz do Sul', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (492, 'Lajeado-Estrela', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (493, 'Cachoeira do Sul', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (494, 'Montenegro', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (495, 'Gramado-Canela', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (496, 'São Jerônimo', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (497, 'Porto Alegre', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (498, 'Osório', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (499, 'Camaquã', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (500, 'Campanha Ocidental', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (501, 'Campanha Central', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (502, 'Campanha Meridional', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (503, 'Serras de Sudeste', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (504, 'Pelotas', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (505, 'Jaguarão', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (506, 'Litoral Lagunar', 'RS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (507, 'Baixo Pantanal', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (508, 'Aquidauana', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (509, 'Alto Taquari', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (510, 'Campo Grande', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (511, 'Cassilândia', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (512, 'Paranaíba', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (513, 'Três Lagoas', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (514, 'Nova Andradina', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (515, 'Bodoquena', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (516, 'Dourados', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (517, 'Iguatemi', 'MS')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (518, 'Aripuanã', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (519, 'Alta Floresta', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (520, 'Colíder', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (521, 'Parecis', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (522, 'Arinos', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (523, 'Alto Teles Pires', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (524, 'Sinop', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (525, 'Paranatinga', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (526, 'Norte Araguaia', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (527, 'Canarana', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (528, 'Médio Araguaia', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (529, 'Alto Guaporé', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (530, 'Tangará da Serra', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (531, 'Jauru', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (532, 'Alto Paraguai', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (533, 'Rosário Oeste', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (534, 'Cuiabá', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (535, 'Alto Pantanal', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (536, 'Primavera do Leste', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (537, 'Tesouro', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (538, 'Rondonópolis', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (539, 'Alto Araguaia', 'MT')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (540, 'São Miguel do Araguaia', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (541, 'Rio Vermelho', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (542, 'Aragarças', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (543, 'Porangatu', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (544, 'Chapada dos Veadeiros', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (545, 'Ceres', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (546, 'Anápolis', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (547, 'Iporá', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (548, 'Anicuns', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (549, 'Goiânia', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (550, 'Vão do Paranã', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (551, 'Entorno de Brasília', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (552, 'Sudoeste de Goiás', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (553, 'Vale do Rio dos Bois', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (554, 'Meia Ponte', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (555, 'Pires do Rio', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (556, 'Catalão', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (557, 'Quirinópolis', 'GO')
INSERT INTO Microregiao (ID_Microregiao, Descricao_Microregiao, Sigla_UF) VALUES (558, 'Brasília', 'DF')

SET IDENTITY_INSERT Microregiao OFF

