CREATE TABLE Mesoregiao (
	ID_Mesoregiao int IDENTITY (1, 1) NOT NULL,
	Descricao_Mesoregiao varchar (max) NOT NULL,
	Sigla_UF char (2) NOT NULL,
	Situacao BIT NULL DEFAULT 1,
	DataInclusao DATETIME NULL DEFAULT GETDATE(),
	DataAlteracao DATETIME NULL,
	DataExclusao DATETIME NULL,
	CONSTRAINT PK_Mesoregiao PRIMARY KEY (ID_Mesoregiao),
	CONSTRAINT FK_UF FOREIGN KEY (Sigla_UF) REFERENCES Unidades_Federacao(Sigla_UF)
)
GO

SET IDENTITY_INSERT Mesoregiao ON

INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (1, 'Madeira-Guaporé', 'RO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (2, 'Leste Rondoniense', 'RO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (3, 'Vale do Juruá', 'AC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (4, 'Vale do Acre', 'AC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (5, 'Norte Amazonense', 'AM')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (6, 'Sudoeste Amazonense', 'AM')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (7, 'Centro Amazonense', 'AM')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (8, 'Sul Amazonense', 'AM')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (9, 'Norte de Roraima', 'RR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (10, 'Sul de Roraima', 'RR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (11, 'Baixo Amazonas', 'PA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (12, 'Marajó', 'PA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (13, 'Metropolitana de Belém', 'PA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (14, 'Nordeste Paraense', 'PA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (15, 'Sudoeste Paraense', 'PA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (16, 'Sudeste Paraense', 'PA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (17, 'Norte do Amapá', 'AP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (18, 'Sul do Amapá', 'AP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (19, 'Ocidental do Tocantins', 'TO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (20, 'Oriental do Tocantins', 'TO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (21, 'Norte Maranhense', 'MA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (22, 'Oeste Maranhense', 'MA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (23, 'Centro Maranhense', 'MA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (24, 'Leste Maranhense', 'MA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (25, 'Sul Maranhense', 'MA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (26, 'Norte Piauiense', 'PI')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (27, 'Centro-Norte Piauiense', 'PI')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (28, 'Sudoeste Piauiense', 'PI')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (29, 'Sudeste Piauiense', 'PI')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (30, 'Noroeste Cearense', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (31, 'Norte Cearense', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (32, 'Metropolitana de Fortaleza', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (33, 'Sertões Cearenses', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (34, 'Jaguaribe', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (35, 'Centro-Sul Cearense', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (36, 'Sul Cearense', 'CE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (37, 'Oeste Potiguar', 'RN')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (38, 'Central Potiguar', 'RN')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (39, 'Agreste Potiguar', 'RN')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (40, 'Leste Potiguar', 'RN')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (41, 'Sertão Paraibano', 'PB')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (42, 'Borborema', 'PB')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (43, 'Agreste Paraibano', 'PB')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (44, 'Mata Paraibana', 'PB')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (45, 'Sertão Pernambucano', 'PE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (46, 'São Francisco Pernambucano', 'PE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (47, 'Agreste Pernambucano', 'PE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (48, 'Mata Pernambucana', 'PE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (49, 'Metropolitana de Recife', 'PE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (50, 'Sertão Alagoano', 'AL')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (51, 'Agreste Alagoano', 'AL')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (52, 'Leste Alagoano', 'AL')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (53, 'Sertão Sergipano', 'SE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (54, 'Agreste Sergipano', 'SE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (55, 'Leste Sergipano', 'SE')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (56, 'Extremo Oeste Baiano', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (57, 'Vale São-Franciscano da Bahia', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (58, 'Centro Norte Baiano', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (59, 'Nordeste Baiano', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (60, 'Metropolitana de Salvador', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (61, 'Centro Sul Baiano', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (62, 'Sul Baiano', 'BA')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (63, 'Noroeste de Minas', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (64, 'Norte de Minas', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (65, 'Jequitinhonha', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (66, 'Vale do Mucuri', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (67, 'Triângulo Mineiro/Alto Paranaíba', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (68, 'Central Mineira', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (69, 'Metropolitana de Belo Horizonte', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (70, 'Vale do Rio Doce', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (71, 'Oeste de Minas', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (72, 'Sul/Sudoeste de Minas', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (73, 'Campo das Vertentes', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (74, 'Zona da Mata', 'MG')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (75, 'Noroeste Espírito-santense', 'ES')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (76, 'Litoral Norte Espírito-santense', 'ES')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (77, 'Central Espírito-santense', 'ES')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (78, 'Sul Espírito-santense', 'ES')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (79, 'Noroeste Fluminense', 'RJ')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (80, 'Norte Fluminense', 'RJ')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (81, 'Centro Fluminense', 'RJ')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (82, 'Baixadas', 'RJ')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (83, 'Sul Fluminense', 'RJ')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (84, 'Metropolitana do Rio de Janeiro', 'RJ')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (85, 'São José do Rio Preto', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (86, 'Ribeirão Preto', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (87, 'Araçatuba', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (88, 'Bauru', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (89, 'Araraquara', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (90, 'Piracicaba', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (91, 'Campinas', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (92, 'Presidente Prudente', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (93, 'Marília', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (94, 'Assis', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (95, 'Itapetininga', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (96, 'Macro Metropolitana Paulista', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (97, 'Vale do Paraíba Paulista', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (98, 'Litoral Sul Paulista', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (99, 'Metropolitana de São Paulo', 'SP')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (100, 'Noroeste Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (101, 'Centro Ocidental Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (102, 'Norte Central Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (103, 'Norte Pioneiro Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (104, 'Centro Oriental Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (105, 'Oeste Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (106, 'Sudoeste Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (107, 'Centro-Sul Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (108, 'Sudeste Paranaense', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (109, 'Metropolitana de Curitiba', 'PR')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (110, 'Oeste Catarinense', 'SC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (111, 'Norte Catarinense', 'SC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (112, 'Serrana', 'SC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (113, 'Vale do Itajaí', 'SC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (114, 'Grande Florianópolis', 'SC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (115, 'Sul Catarinense', 'SC')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (116, 'Noroeste Rio-grandense', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (117, 'Nordeste Rio-grandense', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (118, 'Centro Ocidental Rio-grandense', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (119, 'Centro Oriental Rio-grandense', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (120, 'Metropolitana de Porto Alegre', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (121, 'Sudoeste Rio-grandense', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (122, 'Sudeste Rio-grandense', 'RS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (123, 'Pantanais Sul Mato-grossense', 'MS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (124, 'Centro Norte de Mato Grosso do Sul', 'MS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (125, 'Leste de Mato Grosso do Sul', 'MS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (126, 'Sudoeste de Mato Grosso do Sul', 'MS')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (127, 'Norte Mato-grossense', 'MT')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (128, 'Nordeste Mato-grossense', 'MT')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (129, 'Sudoeste Mato-grossense', 'MT')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (130, 'Centro-Sul Mato-grossense', 'MT')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (131, 'Sudeste Mato-grossense', 'MT')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (132, 'Noroeste Goiano', 'GO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (133, 'Norte Goiano', 'GO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (134, 'Centro Goiano', 'GO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (135, 'Leste Goiano', 'GO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (136, 'Sul Goiano', 'GO')
INSERT INTO Mesoregiao (ID_Mesoregiao, Descricao_Mesoregiao, Sigla_UF) VALUES (137, 'Distrito Federal', 'DF')

SET IDENTITY_INSERT Mesoregiao OFF
