CREATE TABLE SubDistrito (
	ID_SubDistrito int IDENTITY (1, 1) NOT NULL,
	Descricao_SubDistrito varchar (MAX) NULL,
	Sigla_UF char (2) NULL,
	Situacao BIT NULL DEFAULT 1,
	DataInclusao DATETIME NULL DEFAULT GETDATE(),
	DataAlteracao DATETIME NULL,
	DataExclusao DATETIME NULL,
	CONSTRAINT PK_SubDistrito PRIMARY KEY (ID_SubDistrito),
	CONSTRAINT FK_SubDistrito_UF FOREIGN KEY (Sigla_UF) REFERENCES Unidades_Federacao(Sigla_UF)	
)
GO


SET IDENTITY_INSERT SubDistrito ON

INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (1, 'Zona 01', 'RO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (2, 'Zona 02', 'RO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (3, 'Zona 03', 'RO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (4, 'Zona 04', 'RO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (5, 'Primeira R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (6, 'Segunda R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (7, 'Terceira R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (8, 'Quarta R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (9, 'Quinta R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (10, 'Sexta R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (11, 'Sétima R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (12, 'Oitava R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (13, 'Nona R.A.', 'AM')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (14, 'Centro', 'PI')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (15, 'Leste', 'PI')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (16, 'Norte', 'PI')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (17, 'Sudeste', 'PI')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (18, 'Sul', 'PI')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (19, 'Antônio Bezerra', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (20, 'Barra do Ceará', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (21, 'Centro', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (22, 'Mucuripe', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (23, 'Antônio Bezerra', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (24, 'Conjunto Ceará', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (25, 'Cidade dos Funcionários', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (26, 'Messejana', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (27, 'Conjunto Ceará', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (28, 'Prefeito José Walter Mondubim', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (29, 'Parangaba', 'CE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (30, 'R.A. Norte', 'RN')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (31, 'R.A. Sul', 'RN')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (32, 'R.A. Leste', 'RN')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (33, 'R.A. Oeste', 'RN')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (34, 'RPA 01', 'PE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (35, 'RPA 02', 'PE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (36, 'RPA 03', 'PE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (37, 'RPA 04', 'PE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (38, 'RPA 05', 'PE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (39, 'RPA 06', 'PE')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (40, 'Mangabeira', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (41, 'Pampalona', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (42, 'Santana', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (43, 'Santo Antônio', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (44, 'Subae', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (45, 'Amaralina', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (46, 'Brotas', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (47, 'Conceição da Praia', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (48, 'Itapoã', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (49, 'Maré', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (50, 'Mares', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (51, 'Nazaré', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (52, 'Paripe', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (53, 'Passo', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (54, 'Penha', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (55, 'Periperi', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (56, 'Pilar', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (57, 'Pirajá', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (58, 'Plataforma', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (59, 'Santana', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (60, 'Santo Antônio', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (61, 'São Caetano', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (62, 'São Cristovão', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (63, 'São Pedro', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (64, 'Sé', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (65, 'Valéria', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (66, 'Vitória', 'BA')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (67, 'I REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (68, 'II REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (69, 'III REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (70, 'IV REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (71, 'V REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (72, 'VI REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (73, 'VII REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (74, 'VIII REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (75, 'IX REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (76, 'X REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (77, 'XI REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (78, 'XII REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (79, 'XIII REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (80, 'XIV REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (81, 'XV REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (82, 'XVI REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (83, 'XVII REGIÃO ADMINISTRATIVA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (84, 'Centro-Sul', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (85, 'Leste', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (86, 'Nordeste', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (87, 'Noroeste', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (88, 'Oeste', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (89, 'Pampulha', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (90, 'Venda Nova', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (91, 'Barreiro', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (92, 'Nordeste', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (93, 'Norte', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (94, 'Pampulha', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (95, 'Venda Nova', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (96, 'AR. CENTRO', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (97, 'AR. NORTE', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (98, 'AR. JARDIM DAS ALTEROSAS', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (99, 'AR. SANTA CRUZ', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (100, 'AR. IMBIRUÇU', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (101, 'AR. JARDIM TEREZÓPOLIS', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (102, 'AR. CITROLÂNDIA', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (103, 'AR. VIANÓPOLIS', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (104, 'Barra', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (105, '1 Subdistrito', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (106, '2 SUBDISTRITO', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (107, 'Primeiro Subdistrito', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (108, 'Segundo Subdistrito', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (109, '1 Sub-Distrito', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (110, '2 Sub-Distrito', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (111, 'Unidade Territorial I', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (112, 'Unidade Territorial II', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (113, 'Unidade Territorial III', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (114, 'Unidade Territorial IV', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (115, 'Unidade Territorial V', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (116, 'Unidade Territorial VI', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (117, 'Unidade Territorial VII', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (118, 'Unidade Territorial VIII', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (119, 'Unidade Territorial IX', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (120, 'Unidade Territorial X', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (121, 'Unidade Territorial XI', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (122, 'Unidade Territorial XII', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (123, 'Unidade Territorial XIII', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (124, 'Unidade Territorial XIV', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (125, 'Unidade Territorial XV', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (126, 'Unidade Territorial XVI', 'MG')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (127, 'Primeiro Subdistrito', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (128, 'Segundo Subdistrito', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (129, 'Terceiro Subdistrito', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (130, 'Quarto Subdistrito', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (131, 'Barra de Macaé', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (132, 'Aeroporto', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (133, 'Cabiúnas', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (134, 'Imboassica', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (135, 'URG I', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (136, 'URG II', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (137, 'URG III', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (138, 'URG IV', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (139, 'URG V', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (140, 'URG VI', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (141, 'URG VII', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (142, 'URG VIII', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (143, 'URG IX', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (144, 'URG X', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (145, 'URG XI', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (146, 'URG XII', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (147, 'Portuária', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (148, 'Centro', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (149, 'Rio Comprido', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (150, 'Botafogo', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (151, 'Copacabana', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (152, 'Lagoa', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (153, 'São Cristovão', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (154, 'Tijuca', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (155, 'Vila Isabel', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (156, 'Ramos', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (157, 'Penha', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (158, 'Méier', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (159, 'Irajá', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (160, 'Madureira', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (161, 'Jacarepaguá', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (162, 'Bangu', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (163, 'Campo Grande', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (164, 'Santa Cruz', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (165, 'Ilha do Governador', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (166, 'Ilha de Paquetá', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (167, 'Anchieta', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (168, 'Santa Teresa', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (169, 'Barra da Tijuca', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (170, 'Pavuna', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (171, 'Guaratiba', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (172, 'Inhaúma', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (173, 'Rocinha', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (174, 'Jacarezinho', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (175, 'Complexo do Alemão', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (176, 'Maré', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (177, 'Realengo', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (178, 'Cidade de Deus', 'RJ')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (179, 'Administração Regional da Matriz (R.1.MZ)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (180, 'Administração Regional do Boqueirão (R.2.BQ)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (181, 'Administração Regional do Cajuru (R.3.CJ)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (182, 'Administração Regional da Boa Vista (R.4.BV)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (183, 'Administração Regional de Santa Felicidade (R.5.SF)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (184, 'Administração Regional do Portão (R.7.PR)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (185, 'Administração Regional Pinheirinho (R.8.PN)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (186, 'Administração Regional do Bairro Novo (R.10.BN)', 'PR')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (187, 'Capitão Noronha', 'RS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (188, 'Cerro Partido', 'RS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (189, 'Coronel Prestes', 'RS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (190, 'Maria Santa', 'RS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (191, 'Pompeu Machado', 'RS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (192, 'Santa Bárbara', 'RS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (193, 'Região Urbana do Centro', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (194, 'Região Urbana do Prosa', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (195, 'Região Urbana do Segredo', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (196, 'Região Urbana do Imbirussú', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (197, 'Região Urbana do Anhanduizinho', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (198, 'Região Urbana do Bandeira', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (199, 'Região Urbana do Lagoa', 'MS')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (200, 'Administração Regional Norte', 'MT')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (201, 'Administração Regional Centro-Oeste', 'MT')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (202, 'Administração Regional Centro-Leste', 'MT')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (203, 'Administração Regional Norte', 'MT')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (204, 'Administração Regional Centro-Leste', 'MT')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (205, 'Administração Regional Sul-Leste', 'MT')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (206, 'U.T.P. Central', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (207, 'U.T.P. Sul', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (208, 'U.T.P. Marista Bueno', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (209, 'U.T.P. Oeste', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (210, 'U.T.P. Aeroporto', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (211, 'U.T.P. Coimbra', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (212, 'U.T.P. Campinas', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (213, 'U.T.P. Marechal Rondon', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (214, 'U.T.P. Norte Ferroviário', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (215, 'U.T.P. Pedro Ludovico', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (216, 'U.T.P. Bueno-Nova Suiça', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (217, 'U.T.P. Parque Amazônia', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (218, 'U.T.P. Jardim América', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (219, 'U.T.P. Aeroviários', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (220, 'U.T.P. Cidade Jardim', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (221, 'U.T.P. Sudoeste', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (222, 'U.T.P. Jardim Europa', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (223, 'U.T.P. Novo Horizonte', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (224, 'U.T.P. Faiçalville', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (225, 'U.T.P. Jardim Atlântico', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (226, 'U.T.P. Celina Park', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (227, 'U.T.P. Recreio dos Funcionários Públicos', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (228, 'U.T.P. Parque Santa Rita', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (229, 'U.T.P. Parque Oeste Industrial', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (230, 'U.T.P. João Braz', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (231, 'U.T.P. Vila Rizzo', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (232, 'U.T.P. Jardim Petrópolis', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (233, 'U.T.P. Vera Cruz', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (234, 'U.T.P. Chácaras São Joaquim', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (235, 'U.T.P. Vila Regina', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (236, 'U.T.P. Cândida de Morais', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (237, 'U.T.P. Capuava', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (238, 'U.T.P. Maria Dilce', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (239, 'U.T.P. Urias Magalhães', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (240, 'U.T.P. Mutirão', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (241, 'U.T.P. Finsocial', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (242, 'U.T.P. Jardim Balneário Meia Ponte', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (243, 'U.T.P. Mansões Goianas', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (244, 'U.T.P. Campus Universitário', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (245, 'U.T.P. Itatiaia', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (246, 'U.T.P. Goiânia II', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (247, 'U.T.P. Jardim Guanabara', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (248, 'U.T.P. Santa Genoveva', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (249, 'U.T.P. Aeroporto Internacional', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (250, 'U.T.P. Jaó', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (251, 'U.T.P. Ceasa', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (252, 'U.T.P. Santo Hilário', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (253, 'U.T.P. Vila Pedroso', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (254, 'U.T.P. Crimeia Leste', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (255, 'U.T.P. Negrão de Lima', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (256, 'U.T.P. Vila Nova', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (257, 'U.T.P. Bairro Feliz', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (258, 'U.T.P. Leste Universitário', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (259, 'U.T.P. Jardim Goiás', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (260, 'U.T.P. Jardim Novo Mundo', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (261, 'U.T.P. Água Branca', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (262, 'U.T.P. Riviera', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (263, 'U.T.P. Autódromo', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (264, 'U.T.P. Alto da Glória', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (265, 'U.T.P. Santo Antônio', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (266, 'U.T.P. Parque das Laranjeiras', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (267, 'U.T.P. Abadia de Goiás', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (268, 'U.T.P. Parque Bom Jesus', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (269, 'U.T.P. Baliza-Itaipu', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (270, 'U.T.P. São Domingos', 'GO')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (271, 'Brasília', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (272, 'Gama', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (273, 'Taguatinga', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (274, 'Brazlândia', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (275, 'Sobradinho', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (276, 'Planaltina', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (277, 'Paranoá', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (278, 'Riacho Fundo', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (279, 'Núcleo Bandeirante', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (280, 'Ceilândia', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (281, 'Guará', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (282, 'Cruzeiro', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (283, 'Samambaia', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (284, 'Candangolândia', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (285, 'Recanto das Emas', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (286, 'Lago Norte', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (287, 'Lago Sul', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (288, 'Santa Maria', 'DF')
INSERT INTO SubDistrito (ID_SubDistrito, Descricao_SubDistrito, Sigla_UF) VALUES (289, 'São Sebastião', 'DF')

SET IDENTITY_INSERT SubDistrito OFF
