CREATE TABLE Idioma (
	ID_Idioma int IDENTITY (1, 1) NOT NULL,
	Abreviado_Idioma char (2),
	Descricao_Idioma varchar (max),
	Situacao BIT NULL DEFAULT 1,
	DataInclusao DATETIME NULL DEFAULT GETDATE(),
	DataAlteracao DATETIME NULL,
	DataExclusao DATETIME NULL,
	CONSTRAINT PK_Idioma PRIMARY KEY (ID_Idioma)
)
GO

SET IDENTITY_INSERT Idioma ON

INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (1, 'AA', 'Afar')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (2, 'AB', 'Abhkazian')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (3, 'AF', 'Afrikaans')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (4, 'AM', 'Amarico')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (5, 'AR', 'Arabe')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (6, 'AS', 'Assames')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (7, 'AY', 'Aimara')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (8, 'AZ', 'Azerbaidjano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (9, 'BA', 'Bashquir')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (10, 'BB', 'Berbere')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (11, 'BC', 'Baluchi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (12, 'BE', 'Bielo-Russo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (13, 'BG', 'Bulgaro')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (14, 'BH', 'Bihari')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (15, 'BI', 'Bislama')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (16, 'BM', 'Birmanes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (17, 'BN', 'Bengali')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (18, 'BO', 'Tibetano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (19, 'BR', 'Bretao')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (20, 'CA', 'Catalao')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (21, 'CB', 'Cabie')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (22, 'CO', 'Corsico')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (23, 'CR', 'Crioulo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (24, 'CS', 'Tcheco-Eslovaco')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (25, 'CY', 'Gales')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (26, 'DA', 'Dinamarques')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (27, 'DE', 'Alemao')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (28, 'DI', 'Divehi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (29, 'DZ', 'Dzongka')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (30, 'EE', 'Eue')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (31, 'EL', 'Grego')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (32, 'EN', 'Ingles')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (33, 'EO', 'Esperanto')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (34, 'ES', 'Espanhol')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (35, 'ET', 'Estoniano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (36, 'EU', 'Basco')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (37, 'FA', 'Persa')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (38, 'FI', 'Finlandes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (39, 'FJ', 'Fijiano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (40, 'FL', 'Filipino')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (41, 'FO', 'Farsi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (42, 'FR', 'Frances')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (43, 'FY', 'Malaio')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (44, 'GA', 'Irlandes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (45, 'GD', 'Gaelico Escoces')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (46, 'GL', 'Galego')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (47, 'GN', 'Guarani')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (48, 'GU', 'Gujarati')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (49, 'HA', 'Hausa')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (50, 'HI', 'Hindi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (51, 'HR', 'Croata')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (52, 'HU', 'Hungaro')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (53, 'HY', 'Armenio')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (54, 'IA', 'Interlingua')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (55, 'ID', 'Ioma')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (56, 'IE', 'Interlingue')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (57, 'IK', 'Inupiak')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (58, 'IN', 'Indonesio')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (59, 'IS', 'Islandes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (60, 'IT', 'Italiano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (61, 'IW', 'Hebraico')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (62, 'JA', 'Japones')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (63, 'JI', 'Iidiche')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (64, 'JV', 'Javanes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (65, 'KA', 'Georgiano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (66, 'KK', 'Casaque')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (67, 'KL', 'Groenlandes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (68, 'KM', 'Cambodjano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (69, 'KN', 'Canadense')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (70, 'KO', 'Coreano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (71, 'KS', 'Cachemiriano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (72, 'KU', 'Curdo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (73, 'KY', 'Quirquiz')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (74, 'LA', 'Latim')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (75, 'LN', 'Lingua')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (76, 'LO', 'Laosiano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (77, 'LP', 'Lapes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (78, 'LT', 'Lituano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (79, 'LV', 'Letao')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (80, 'LX', 'Luxemburgues')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (81, 'MA', 'Mandingo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (82, 'MG', 'Malgaxe')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (83, 'MI', 'Maori')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (84, 'MK', 'Macedonio')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (85, 'ML', 'Malaiala')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (86, 'MN', 'Mongol')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (87, 'MO', 'Moldavio')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (88, 'MR', 'Marates')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (89, 'MS', 'Malaio')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (90, 'MT', 'Maltes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (91, 'MY', 'Sirmanes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (92, 'NA', 'Nauruano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (93, 'NE', 'Nepali')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (94, 'NL', 'Holandes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (95, 'NO', 'Noruegues')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (96, 'OM', 'Oromo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (97, 'OR', 'Oria')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (98, 'OU', 'Outros')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (99, 'PA', 'Punjabi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (100, 'PL', 'Polones')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (101, 'PS', 'Pushto')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (102, 'PT', 'Portugues')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (103, 'QI', 'Quisuahili')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (104, 'QU', 'Quichua')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (105, 'RM', 'Reto-Romano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (106, 'RN', 'Quirundi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (107, 'RO', 'Romeno')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (108, 'RU', 'Russo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (109, 'RW', 'Quiniaruanda')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (110, 'SA', 'Sanscrito')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (111, 'SD', 'Sindi')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (112, 'SG', 'Sango')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (113, 'SH', 'Servo-Croata')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (114, 'SI', 'Cingales')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (115, 'SK', 'Eslovaco')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (116, 'SL', 'Esloveno')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (117, 'SM', 'Samoano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (118, 'SN', 'Shona')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (119, 'SO', 'Somali')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (120, 'SQ', 'Albanes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (121, 'SR', 'Serbian')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (122, 'SS', 'Sisvati')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (123, 'ST', 'Sesoto')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (124, 'SU', 'Sudanes')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (125, 'SV', 'Suco')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (126, 'SW', 'Suaili')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (127, 'TA', 'Tamil')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (128, 'TE', 'Telugo')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (129, 'TG', 'Tadjique')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (130, 'TH', 'Tai')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (131, 'TI', 'Tigrina')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (132, 'TK', 'Turcomano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (133, 'TL', 'Talagog')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (134, 'TN', 'Setsuana')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (135, 'TO', 'Tongales')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (136, 'TR', 'Turco')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (137, 'TS', 'Tsonga')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (138, 'TT', 'Tatar')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (139, 'TU', 'Tuvaloano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (140, 'TW', 'Tui')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (141, 'UK', 'Ucraniano')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (142, 'UR', 'Urdu')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (143, 'UZ', 'Uzbeco')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (144, 'VI', 'Vietnamita')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (145, 'VO', 'Volupak')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (146, 'WO', 'Wolof')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (147, 'XH', 'Xosa')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (148, 'YO', 'Yoruba')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (149, 'ZH', 'Chines')
INSERT INTO Idioma (ID_Idioma, Abreviado_Idioma, Descricao_Idioma) VALUES (150, 'ZU', 'Zules')

SET IDENTITY_INSERT Idioma OFF
